project:
  type: website

website:
  title: "Alexander Enge"
  site-url: https://alexenge.github.io
  description: The personal website of Alexander Enge
  repo-url: https://github.com/alexenge/alexenge.github.io
  image: images/logo.png
  search: false
  sidebar:
    style: floating
    logo: images/logo.png
    logo_alt: |
      In black, the lower-case danish letter æ,
      combining the initials of my name (A and E).
    background: "#ffffff"
    foreground: "#000000"
    contents:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks & posters
  favicon: images/favicon.png
  google-analytics: "G-R5BP5B7W54"
  twitter-card:
    title: Alexander Enge
    description: The personal website of Alexander Enge
    image: images/logo.png
    image-alt: |
      In black, the lower-case danish letter æ,
      combining the initials of my name (A and E).
    image-width: 500
    image-height: 500
    card-style: summary
    creator: "@alexenge"
    site: "@alexenge"
  open-graph:
    image: images/logo.png
    image-alt: |
      In black, the lower-case danish letter æ,
      combining the initials of my name (A and E).
    image-width: 500
    image-height: 500
    locale: en-US
  page-footer:
    center: |
      Copyright 2023, Alexander Enge<br>
      Made with <a href="https://quarto.org" target="_blank">Quarto</a> --
      Code on <a href="https://github.com/alexenge/alexenge.github.io" target="_blank">GitHub</a>
    foreground: "#000000"

format:
  html:
    theme: assets/theme.scss
    css: assets/styles.css
    toc: false
    grid:
      sidebar-width: 150px
      body-width: 720px

execute:
  freeze: auto
