---
title: "Curriculum vitae"
---

## Education

* **2021–today**: PhD student, Max Planck Institute for Human Cognitive and Brain Sciences and Humboldt-Universität zu Berlin
* **2019–2021**: MSc in Psychology, Humboldt-Universität zu Berlin
* **2016–2019**: BSc in Psychology, Humboldt-Universität zu Berlin

## Jobs & internships

* **2017–2021**: Research assistant, Abdel Rahman Lab for Neurocognitive Psychology, Humboldt-Universität zu Berlin
* **2019**: Research internship, Department of Neuropsychology, Max Planck Institute for Human Cognitive and Brain Sciences
* **2019**: Research work experience, Social Networks Lab, Royal Holloway, University of London
* **2018**: Research internship, Biological Psychology Lab, Humboldt-Universität zu Berlin
* **2018**: Research internship, Abdel Rahman Lab for Neurocognitive Psychology, Humboldt-Universität zu Berlin

## Awards & scholarships

* **2021–today**: PhD scholarship, German Academic Scholarship Foundation (Studienstiftung des deutschen Volkes)
* **2019–2021**: Undergraduate scholarship, German Academic Scholarship Foundation (Studienstiftung des deutschen Volkes)
* **2021**: Best MSc degree in Psychology, Humboldt-Universität zu Berlin
* **2019**: Best BSc degree in Psychology, Humboldt-Universtität zu Berlin

## Volunteer & committee work

* **2021–today**: <a href="https://www.cbs.mpg.de/en/cbs-open-science" target="_blank">Open Science Initiative</a>, Max Planck Institute for Human Cognitive and Brain Sciences
* **2021–today**: <a href="https://www.cbs.mpg.de/phd-representatives" target="_blank">PhD representative</a>, Max Planck Institute for Human Cognitive and Brain Sciences
* **2018–2021**: Undergraduate student representative, Department of Psychology, Humboldt-Universität zu Berlin
* **2016–2021**: <a href="http://studieren-ohne-grenzen.org/en" target="_blank">Studies Without Borders</a>, Berlin group

## Publications

* **Enge, A.**, Süß, F., & Rahman, R. A. (2023). <a href="https://doi.org/10.1523/JNEUROSCI.2038-22.2023" target="_blank">Instant effects of semantic information on visual perception</a>. *Journal of Neuroscience*
* Aristei, S., …, **Enge, A.**, et al. (2022). <a href="https://doi.org/10.1080/23273798.2022.2085312" target="_blank">Affect as Anaesthetic: How emotional contexts modulate the processing of counterintuitive concepts</a>. *Language, Cognition and Neuroscience*
* **Enge, A.**, Abdel Rahman, R., & Skeide, M. A. (2021). <a href="https://doi.org/10.1016/j.neuroimage.2021.118436" target="_blank">A meta-analysis of fMRI studies of semantic cognition in children</a>. *NeuroImage*
* **Enge, A.**, Friederici, A. D., & Skeide, M. A. (2020). <a href="https://doi.org/10.1016/j.neuroimage.2020.116858" target="_blank">A meta-analysis of fMRI studies of language comprehension in children</a>. *NeuroImage*

Go to [Publications](publications.qmd) for the full list

## Talks & posters

* **Enge, A.**, Mahajan, V., Huettig, F., & Skeide, M. A. (2023). Densely sampling the development of multisensory mapping while learning to read. *Psychologie und Gehirn*
* **Enge, A.**, Friederici, A. D., Abdel Rahman, R., & Skeide, M. A. (2022). Meta-analyzing the cortical networks for language and semantics in children. *14th Annual Meeting of the Society for the Neurobiology of Language*
* **Enge, A.** & Skeide, M. A. (2022). Seeing language: How learning to read connects vision and speech. *CO-AIR: Current Opinion on Audiovisual Integration and Reading*
* **Enge, A.**, Süß, F., & Abdel Rahman, R. (2021). Event-related potentials of the semantically informed perception of unfamiliar objects. *Tagung experimentell arbeitender Psychologen*

Go to [Talks & posters](talks.qmd) for the full list

## Open source software

* **<a href="https://github.com/alexenge/hu-neuro-pipeline" target="_blank">hu-neuro-pipeline</a>**: Single trial EEG pipeline at the Abdel Rahman Lab for Neurocognitive Psychology, Humboldt-Universität zu Berlin
* Contributed to <a href="https://nimare.readthedocs.io" target="_blank">NiMARE</a>, <a href="https://nilearn.github.io/stable/index.html" target="_blank">Nilearn</a>

## Workshops & summer schools

* **Neuromatch Academy, Computational Neuroscience** (2021) – Interactive student
* **Tools for theory: Improving the theoretical foundations of psychological science** (2021) – Event series co-organized with Katarzyna Gugnowska

## Peer review

* Cerebral Cortex, Developmental Science, Psychophysiology

## Skills

* **Neural data analysis**: EEG, fMRI, VBM, DTI
* **Programming**: Python, R, MATLAB
* **Statistics**: Linear mixed-effects modeling, machine learning, Bayesian statistics, meta-analysis
* **Reproducibility**: git, GitHub, Docker/Singularity, DataLad
* **Languages**: German (native), English (TOEFL 111/120), Danish, Spanish, Latin (basic)
* **Sports**: Long distance runner (2:45 h Marathon) at SC DHfK Leipzig
