---
title: "Talks & posters"
---

## 2024

* **Enge, A.**, Huettig, & Skeide, M. A. (2024). Leveraging dense-sampling fMRI to test the expansion and renormalization of BOLD responses caused by learning interventions. *Psychologie und Gehirn*

## 2023

* **Enge, A.**, Huettig, F., Mahajan, V., & Skeide, M. A. (2023). Individual differences in brain activation changes while learning to read a non-alphabetic script. *Fachgruppentagung Entwicklungspsychologie*
* **Enge, A.**, Mahajan, V., Huettig, F., & Skeide, M. A. (2023). How reading instruction shapes brain responses in individual children. *EARLI*
* **Enge, A.**, Mahajan, V., Huettig, F., & Skeide, M. A. (2023). Densely sampling the development of multisensory mapping while learning to read. *Psychologie und Gehirn*

## 2022

* **Enge, A.**, Friederici, A. D., Abdel Rahman, R., & Skeide, M. A. (2022). Meta-analyzing the cortical networks for language and semantics in children. *Annual Meeting of the Society for the Neurobiology of Language*
    * <a href="https://github.com/alexenge/snl_2022" target="_blank">Slides</a>
* Eiserbeck, A., **Enge, A.**, Rabovsky, M., & Abdel Rahman, R. (2022). Graded conscious perception during the attentional blink. *Annual meeting of the Association for the Scientific Study of Consciousness*
* **Enge, A.** & Skeide, M. A. (2022). Seeing language: How learning to read connects vision and speech. *CO-AIR: Current Opinion on Audiovisual Integration and Reading*

## 2021

* **Enge, A.**, Süß, F., & Abdel Rahman, R. (2021). Understanding object function instantly shapes perception within less than 200 ms. *Psychologie und Gehirn*
* **Enge, A.**, Süß, F., & Abdel Rahman, R. (2021). Event-related potentials of the semantically informed perception of unfamiliar objects. *Tagung experimentell arbeitender Psychologen*

## 2019

* Eiserbeck, A., **Enge, A.**, & Abdel Rahman, R. (2019). Trust before first sight: Effects of person knowledge on visual awareness of faces. *Psychologie und Gehirn*
* Eiserbeck, A., **Enge, A.**, & Abdel Rahman, R. (2019). Investigating effects of person knowledge and facial trustworthiness on the access to visual awareness. *Tagung experimentell arbeitender Psychologen*
